### ISSUE TITLE
Check SPI Mode

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-mqtt#10]
https://github.com/quartiq/thermostat-mqtt/blob/2fed79662b277d2fdb5d806382128207e7e145b6/src/dac.rs#L26
Somehow it seems that capture on first transition is correct on Thermostat-EEM. Not sure why. I think I copied this from m-labs Thermostat code.

**Comment by jordens** [comment]
Doesn't matter. There is no MISO.

**Comment by SingularitySurfer** [comment]
That's strange, I see different output voltages on the different modes..

**Comment by jordens** [comment]
Well either idle low and capture second or idle high and capture first.

**Comment by SingularitySurfer** [comment]
More debugging necessary, currently I see 1.5V (which I expect) with capture first and idle low. But there could be other things going on and other voltages come out different from what I expect.

**Comment by SingularitySurfer** [comment]
So the 1.5V looking right was just a funny coincidence. Thermostat-EEM has 3V ref, while Thermostat has 5V. With the wrong reference and the wrong SPI mode the right 1.5V appear, but the other voltages are off.

**Comment by SingularitySurfer** [comment]
Likely I just saw some start-up glitching and that's why the bits were sometimes misaligned by one bit. Using proper sync addressing everything works fine now with idle low/capture second as on Thermostat-2CH.
